name: FlutterCi  #CI名称
on: [push]  #触发条件为push操作

jobs:
  check:
    name: Test on ${{ matrix.os }}  #运行在哪个平台 macos
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1  #三方flutter的Action，它可以在服务器配置一个flutter环境
      - uses: subosito/flutter-action@v1
        with: 
          flutter-version: '3.16.8'
          channel: 'stable'

      - run: cd flutter_module && flutter build ios-framework --cocoapods --output=../FlutterModuleDemo/Flutter
      - run: |
         git add .
         git commit -m 'update flutter framework'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUIB_TOKEN }}
